default: &default
  app_url: "http://localhost:3000"
  static_pages:
    home: "http://localhost:3000/static_pages/home"
    help: "http://localhost:3000/static_pages/help"
    contact: "http://localhost:3000/static_pages/contact"
  signup: "http://localhost:3000/signup"
  outsideLink:
    railsTutorial: "http://www.railstutorial.org"
    railsTutorialHelp: "http://www.railstutorial.org/help"
    railsTutorialBook: "http://www.railstutorial.org/book"
  email:
    format: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
    maxLength: 256
  userName:
    maxLength: 50
  password:
    minLength: 6
  user_pagination:
    per_page: 10
  avatar:
    size: 50
    mini_size: 30
  password_reset:
    expired: 2
  digit_140: 140
  page_10: 10
  image:
    fileSize: 5
    type: 
      - image/jpeg
      - image/png
      - image/gif
    size: [500, 500]
development:
  <<: *default
